#!/usr/bin/env sh


echo "welcome! starting now."

if [ "$1" = "both" ]; then
  sh ./install.sh
  sh ./config.sh
elif [ "$1" = "install" ]; then
  sh ./install.sh
elif [ "$1" = "config" ]; then
  sh ./config.sh
else
  echo "please choose an option"
  exit 1
fi

echo "do you want to reboot the system now? [y/N] "
read -r option
if [ "$option" = 'y' ] || [ "$option" = 'Y' ]; then
  sudo reboot
fi
