#!/usr/bin/env sh


install() {
  sh ./components/fedora.sh
  sh ./components/install_apps.sh
}

config() {
  sh ./components/gnome.sh
  sh ./components/python.sh
  sh ./components/rust.sh
  sh ./components/git.sh
  sh ./components/dotfiles.sh
  # printf "\t- cloning eyecandy..."
  # sh ./components/eyecandy.sh "$machine"
  printf "\t- setting zsh as default shell...\n"
  if [ "$SHELL" != "/bin/zsh" ]; then
    chsh -s /bin/zsh
  fi
}

ask_if_reboot() {
  printf "\n\n\033[33mdo you want to reboot the system now?\033[0m [y/N]\n"
  read option
  if [ "$option" = 'y' ] || [ "$option" = 'Y' ]; then
    sudo reboot
  fi
}

printf "\n\033[36mwelcome!\033[0m\n\n"

if [ "$1" = "both" ]; then
  printf "\033[32minstalling and configuring everything...\033[0m\n"
  install
  config
  ask_if_reboot
elif [ "$1" = "install" ]; then
  printf "\033[32monly running installing scripts...\033[0m\n"
  install
  ask_if_reboot
elif [ "$1" = "config" ]; then
  printf "\033[32monly running configuration scripts...\033[0m\n"
  config
else
  printf "\033[33mplease rerun the command with an option:\033[0m\n"
  printf "\t'./run both' to install and configure everything.\n"
  printf "\t'./run config' to only configure everything.\n"
  printf "\t'./run install' to only install everything.\n"
  exit 1
fi

